server:
  port: 8080

spring:
  dubbo:
    application: user-web           #dubbo中的服务名称
    registry:
      address: 192.168.65.130:2181      #zookeeper注册中心的地址
      protocol: zookeeper               #zookeeper通讯协议名称
    protocol:
      name: dubbo                       #dubbo的通讯协议名称
    base-package: com.personage.gmall   #dubbo的服务扫描路径
    consumer:
      timeout: 600000                   #设置超时时间
      check: false                      #检查服务是否存在
#  datasource:
#    url: jdbc:mysql://localhost:3306/gmall_study?serverTimezone=GMT&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
#    username: root
#    password: root123
#    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  configuration:
#    map-underscore-to-camel-case: true
#使用通用Mapper后自动转换
#  configuration:
#    map-underscore-to-camel-case: true #数据库下划线转为java驼峰命名

logging:
  level:
    root: debug
